In [19]:
import numpy as np
import random
#Input array

X = np.array([[1, 0, 1, 0], [1 ,0 ,1 ,1 ],[ 0 , 1 , 0 , 1 ]])

#Output
y = np.array([[1], [1], [0]])

In [2]:
#Sigmoid Function
def sigmoid(x): 
    return  1/(1+np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x): 
    return x*(1-x)

In [13]:
#Variable initialization
epoch = 5000 #Setting training iterations
lr = 0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set 
print("inputlayer_neurons=%s"%(inputlayer_neurons))
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

inputlayer_neurons=4


In [22]:
#weight and bias initialization
random.seed(1)
wh = np.random.uniform( size = ( inputlayer_neurons , hiddenlayer_neurons ) ) 
bh = np.random.uniform( size = ( 1 , hiddenlayer_neurons ) ) 
wout = np.random.uniform( size = ( hiddenlayer_neurons , output_neurons ) ) 
bout = np.random.uniform( size = ( 1 , output_neurons ) )

# 作業 
* 請參閱範例中的 hidden Layer 寫法, 完成 output Layer 的程式

In [23]:

for i in  range ( epoch ) :
    #Forward Propogation
    hidden_layer_input1 = np.dot(X, wh) 
    hidden_layer_input = hidden_layer_input1 + bh
    hiddenlayer_activations =  sigmoid( hidden_layer_input ) 
print(X)
print(hiddenlayer_activations)

[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]
[[0.86883655 0.84391307 0.72222406]
 [0.94623636 0.90776674 0.84157083]
 [0.89186676 0.83757117 0.83212986]]


In [24]:
for i in  range ( epoch ) :
    '''
    寫出output Layer
    '''
    hidden_layer_input1 = np.dot(hiddenlayer_activations, wout) 
    hidden_layer_input = hidden_layer_input1 + bout
    output = sigmoid( hidden_layer_input ) 
    
print ( "output of Forward Propogation:\n{}" .format(output)) 
print ( "wout,bout of Backpropagation:\n{},\n{}" .format(wout, bout ))

output of Forward Propogation:
[[0.87473427]
 [0.88586933]
 [0.88012814]]
wout,bout of Backpropagation:
[[0.65964884]
 [0.23625193]
 [0.33180928]],
[[0.93133911]]
